[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']

# 编译器设置
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200
via_ir = true

# 不将警告视为错误
deny = "warnings"

# 额外输出
extra_output = ['metadata']
extra_output_files = ['metadata']

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = true